import Link from 'next/link';
import Layout from 'shared/dist/layout/Layout';
import 'shared/dist/styles/global.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Layout
          linkComponent={Link as React.ComponentType<React.LinkHTMLAttributes<HTMLLinkElement>>}>
          {children}
        </Layout>
      </body>
    </html>
  )
}
